
<h2>Admintools Password Generator</h2>
-------------------------------------------------------------
<p>Use this username & password to login.</p><br>

<h3>username: {{$username}}</h3>
<h3>password: {{$password}}</h3><br>

<h3>Password was generated by {{$generated_by}}</h3>
-------------------------------------------------------------
<p>Please do not reply to this mail.</p>
